### ISSUE TITLE
Transform into pdf

### ISSUE THREAD

**Issue by MrChoclate** [Atilla-Learn/app-hybrides#2]
@neeev my print-pdf seems to be broken, any idea?

**Comment by AntoineGirard** [comment]
I am going to find solution

On 02/15/2016 03:41 PM, Clément VILLAIN wrote:

> @neeev https://github.com/neeev my print-pdf seems to be broken, any idea?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Atilla-Learn/app-hybrides/issues/2.

## 

Antoine Girard
Etudiant EISTI - Responsable communication ATILLA
antoine.girard@eisti.eu
06 28 19 28 65

**Comment by Wonskcalb** [comment]
Why should this be done ? We now have a version of the slides online.

**Comment by Alterrien** [comment]
I don't think we need a pdf for that, as long as the slides are available on slides.atilla.org.

**Comment by Wonskcalb** [comment]
I agree
